class Parameters:

  def __init__(
          self,
          PATH_TO_SEQUENCES,
          PATH_TO_BORDERS,
          PATH_TO_CONTOURS,
          PATH_TO_CF,
          PROCESS_FULL_SEQUENCE,
          PATCH_HEIGHT,
          PATCH_WIDTH,
          OVERLAPPING,
          DESIRED_SPATIAL_RESOLUTION,
          PATH_WALL_SEGMENTATION_RES,
          PATH_TO_LOAD_TRAINED_MODEL_WALL
  ):

    self.PATH_TO_SEQUENCES=PATH_TO_SEQUENCES
    self.PATH_TO_BORDERS=PATH_TO_BORDERS
    self.PATH_TO_CONTOURS=PATH_TO_CONTOURS
    self.PATH_TO_CF=PATH_TO_CF
    self.PROCESS_FULL_SEQUENCE=PROCESS_FULL_SEQUENCE
    self.PATCH_HEIGHT=PATCH_HEIGHT
    self.PATCH_WIDTH=PATCH_WIDTH
    self.OVERLAPPING=OVERLAPPING
    self.DESIRED_SPATIAL_RESOLUTION=DESIRED_SPATIAL_RESOLUTION
    self.PATH_WALL_SEGMENTATION_RES=PATH_WALL_SEGMENTATION_RES
    self.PATH_TO_LOAD_TRAINED_MODEL_WALL=PATH_TO_LOAD_TRAINED_MODEL_WALL